# Generated by tinfoil 0.2.19.
# This file is a template. `mix tinfoil.homebrew` fills in version,
# URLs, and SHA256 checksums from the published release assets and
# pushes the result to the tap repo.
class TinfoilDemo < Formula
  desc "tinfoil_demo CLI"
  homepage "https://github.com/joshrotenberg/tinfoil_demo"
  version "0.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.9.0/tinfoil_demo-0.9.0-aarch64-apple-darwin.tar.gz"
      sha256 "5e11c95b089140a200de81ae4282e29fe9d85e9d38c6a71430ec97e2c23d0e75"
    end
    on_intel do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.9.0/tinfoil_demo-0.9.0-x86_64-apple-darwin.tar.gz"
      sha256 "1aae04a19aee31e87ac567e44656d6d7bfdcefc6fa154c213223fc0ec16a2ee5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.9.0/tinfoil_demo-0.9.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c8689577c5b36cb587798689a10a9292f57822247df09780cce0e0197ca2ceb6"
    end
    on_intel do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.9.0/tinfoil_demo-0.9.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "8c53872478f943f6c2fdf1bd29c1f7584c63975e35f63b38a8fe65cb62a7b930"
    end
  end

  def install
    bin.install "tinfoil_demo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tinfoil_demo --version")
  end
end
