# Generated by tinfoil 0.2.18.
# This file is a template. `mix tinfoil.homebrew` fills in version,
# URLs, and SHA256 checksums from the published release assets and
# pushes the result to the tap repo.
class TinfoilDemo < Formula
  desc "tinfoil_demo CLI"
  homepage "https://github.com/joshrotenberg/tinfoil_demo"
  version "0.8.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.8.0/tinfoil_demo-0.8.0-aarch64-apple-darwin.tar.gz"
      sha256 "5e3bff013f2daa93bdeacd1942c2f8d4e3c75a676a4f9c40ab1887f40dcb786a"
    end
    on_intel do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.8.0/tinfoil_demo-0.8.0-x86_64-apple-darwin.tar.gz"
      sha256 "bbdb4ff57bdaddc5614fb91c07b55667df8deb4f6fd60be51c5d58852c5e3fe0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.8.0/tinfoil_demo-0.8.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "2b05695565bdc80afad4e9caf34e0c68feee82030b8991751abc7f8d115d4e83"
    end
    on_intel do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.8.0/tinfoil_demo-0.8.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3d53e300d2e0e69ed8fff9c6c8cec6b4db0d586f37bbe8a613d508ead7b1e7ad"
    end
  end

  def install
    bin.install "tinfoil_demo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tinfoil_demo --version")
  end
end
