# Generated by tinfoil 0.2.20.
# This file is a template. `mix tinfoil.homebrew` fills in version,
# URLs, and SHA256 checksums from the published release assets and
# pushes the result to the tap repo.
class TinfoilDemo < Formula
  desc "tinfoil_demo CLI"
  homepage "https://github.com/joshrotenberg/tinfoil_demo"
  version "0.10.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.10.0/tinfoil_demo-0.10.0-aarch64-apple-darwin.tar.gz"
      sha256 "60a4f4e35abc98ca863f571f4a9aaa16663f186533180c617cc222ad620d291e"
    end
    on_intel do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.10.0/tinfoil_demo-0.10.0-x86_64-apple-darwin.tar.gz"
      sha256 "ff2d0cb1666b9fced75477f5a88f5614b5dd7f0492986362d0c20bc1768c23dc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.10.0/tinfoil_demo-0.10.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "7d3b8ae108cc62f2cf6a1c2d413f30b3655c6885d5fdc67b55e9dce6a8111a15"
    end
    on_intel do
      url "https://github.com/joshrotenberg/tinfoil_demo/releases/download/v0.10.0/tinfoil_demo-0.10.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "ebc895916a4d3da944765a411d0516275c94d59cfbe4f02adf37e2fb038d7777"
    end
  end

  def install
    bin.install "tinfoil_demo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tinfoil_demo --version")
  end
end
